//@ts-nocheck
import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/components/Provider";
import Appbar from "@/components/Appbar";
import Footer from "@/components/Footer";

import { SearchProvider } from "@/context/searchContext";

export const metadata: Metadata = {
	title: "Saas Blog",
	description: "Blog site Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className='min-h-screen flex flex-col'>
				<Provider>
					{" "}
					<SearchProvider>
						<Appbar />
						<main className='flex-1'>{children}</main>
						<Footer />{" "}
					</SearchProvider>
				</Provider>
			</body>
		</html>
	);
}
